name: flutter_app
description: A new Flutter application.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: any
  intl: any
  sqflite: ^2.0.0+3
  scoped_model: ^1.1.0
  path_provider: ^2.0.2
  url_launcher: ^6.0.3
  fluttertoast: ^8.0.6
  flutter_webview_plugin: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/